### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ksami** [nolmoonen/cuda-lbvh#1]
Hi @nolmoonen,

Thank you for releasing this very helpful project.

I've noticed that it is missing a license, though I see that another of your projects has an MIT license (https://github.com/nolmoonen/jpeggpu), I don't think I can assume that applies to all your projects.

Could I ask what the license of cuda-lbvh is please?

Thank you.

**Comment by nolmoonen** [comment]
Thanks for checking out my project! I understand the need for a license, but unfortunately open source licenses are a complex topic and I am no expert. This repository contains code that belongs to NVIDIA (in `deps/sutil`) and falls under their 3-Clause BSD License, there is code that is written by me, and the scenes have Creative Commons licenses (reference to [Computer Graphics Archive](https://casual-effects.com/data) is also in the README). I'm not sure if I can assign a single license to the entire project. In the hope it helps you, I made a commit just now that adds an MIT license to the code that is written by me. If you let me know your use case, maybe I can help you better.

**Comment by ksami** [comment]
Thank you for adding the license headers and explanation that's good enough for me. If it helps, I've seen other repositories add a section on licenses in their [README or LICENSE file](https://github.com/CGAL/cgal-swig-bindings?tab=License-1-ov-file), or perhaps [another LICENSE file](https://github.com/numba/numba/blob/main/LICENSES.third-party)
